/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package psw

import kotlin.test.Test
import kotlin.test.assertEquals

class PasswordValidatorTest {
    private val passwordValidator = PasswordValidator()

    @Test fun passwordLessOrEqual8Length_shouldNot_be_valid() {
        val passLessOrEqual8 = "12345678"
        assertEquals(false, passwordValidator.valid(passLessOrEqual8))
    }

    @Test fun password_should_containsACapitalLetter() {
        val passAllLowerCase = "abcdefghij"
        assertEquals(false, passwordValidator.valid(passAllLowerCase))
    }

    @Test fun validPassword_be_valid() {
        val validPassword = "12345678A"
        assertEquals(true, passwordValidator.valid(validPassword))
    }
}
